p8105\_hw3\_at3343
================
Alice Tivarovsky
10/6/2019

# P8105 Homework 3

Setup

## Problem 1

### Instacart Data

Loading data and generating preview:

``` r
library(p8105.datasets)
data("instacart")
view(head(instacart, n = 50))
```

The instacart dataset contains 1,384,617 observations and 15 variables.
It catalogues instacart orders from October 2017 in New York City. Key
variables include order\_id (the order identifier), user\_id (the
customer identifier), product\_id (the product name within each order),
and order\_dow (the day of the week). The first row, for example, is
order\_id = 1, meaning it was the first order in October 2017, includes
(among 7 other items) the item product\_name = Bulgarian Yogurt, which
was ordered by customer user\_id = 112108 on order\_dow = 4 (presumably
Wednesday).

## EDA with Instacart Dataset

Counting \# of aisles and aisles most commonly ordered from.

``` r
pop_aisle = 
  count(instacart, aisle_id) %>% 
  arrange(desc(n))

pop_aisle
```

    ## # A tibble: 134 x 2
    ##    aisle_id      n
    ##       <int>  <int>
    ##  1       83 150609
    ##  2       24 150473
    ##  3      123  78493
    ##  4      120  55240
    ##  5       21  41699
    ##  6      115  36617
    ##  7       84  32644
    ##  8      107  31269
    ##  9       91  26240
    ## 10      112  23635
    ## # … with 124 more rows

There are 134 aisles and the aisle most commonly ordered from is aisle
83 (150609 items).

Keeping only aisles with n \> 10,000, creating a plot that shows the
number of items ordered in each aisle.
